# Generated by Django 4.1.7 on 2023-03-21 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_assignment_assignmentsolution_company_job_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_moderator",
            new_name="is_staff",
        ),
    ]
