# Generated by Django 4.1.7 on 2023-03-21 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_is_moderator_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionsolutioncomments",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="questionsolutioncomments",
            name="question_solution",
        ),
        migrations.DeleteModel(
            name="AssignmentSolutionComments",
        ),
        migrations.DeleteModel(
            name="QuestionSolutionComments",
        ),
    ]
