# Generated by Django 4.1.7 on 2023-03-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_questionsolutioncomments_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("post_type", models.CharField(max_length=32)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.job"
                    ),
                ),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("thumbs_up", models.IntegerField()),
                ("thumbs_down", models.IntegerField()),
                ("solution", models.TextField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.post"
                    ),
                ),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "post_solution",
                "verbose_name_plural": "post_solutions",
            },
        ),
        migrations.RemoveField(
            model_name="assignmentsolution",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="assignmentsolution",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="job",
        ),
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
        migrations.RemoveField(
            model_name="questionsolution",
            name="question",
        ),
        migrations.RemoveField(
            model_name="questionsolution",
            name="user",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="AssignmentSolution",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="QuestionSolution",
        ),
    ]
