# Generated by Django 4.1.7 on 2023-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_user_first_name_user_last_name_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsolution",
            name="thumbs_down",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postsolution",
            name="thumbs_up",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
