# Generated by Django 4.1.7 on 2023-03-31 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_post_users_remove_postsolution_thumbs_down_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="users",
            field=models.ManyToManyField(
                related_name="user_post_votes",
                through="core.PostVotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postsolution",
            name="users",
            field=models.ManyToManyField(
                related_name="user_postsolution_votes",
                through="core.PostSolutionVotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
