# Generated by Django 4.1.7 on 2023-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_post_users_postsolution_users"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postsolutionvotes",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postvotes",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="postsolutionvotes",
            constraint=models.UniqueConstraint(
                fields=("user", "postsolution"), name="unique_postsolution_liking"
            ),
        ),
        migrations.AddConstraint(
            model_name="postvotes",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_post_liking"
            ),
        ),
    ]
