# Generated by Django 4.1.7 on 2023-04-22 13:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_postsolutionvotes_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.RemoveField(
            model_name="postsolution",
            name="solution",
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postsolution",
            name="content",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
