# Generated by Django 4.1.7 on 2023-05-02 14:26

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_post_description_remove_post_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="users",
            new_name="votes",
        ),
        migrations.RenameField(
            model_name="postsolution",
            old_name="users",
            new_name="votes",
        ),
        migrations.RemoveField(
            model_name="company",
            name="country",
        ),
        migrations.RemoveField(
            model_name="job",
            name="seniority",
        ),
        migrations.AddField(
            model_name="post",
            name="seniority",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="years_experience",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CompanyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.company"
                    ),
                ),
                (
                    "jobs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.job"
                    ),
                ),
            ],
            options={
                "verbose_name": "company_job",
                "verbose_name_plural": "company_jobs",
            },
        ),
        migrations.RemoveField(
            model_name="job",
            name="companies",
        ),
        migrations.AddField(
            model_name="job",
            name="companies",
            field=models.ManyToManyField(
                related_name="job_compaines",
                through="core.CompanyJob",
                to="core.company",
            ),
        ),
    ]
