# Generated by Django 4.1.7 on 2023-05-02 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_users_post_votes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyjob",
            old_name="jobs",
            new_name="job",
        ),
    ]
