# Generated by Django 4.1.7 on 2023-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_jobs_companyjob_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
