# Generated by Django 4.1.7 on 2023-05-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_post_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="job",
        ),
        migrations.AddField(
            model_name="post",
            name="CompanyJob",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.companyjob",
            ),
            preserve_default=False,
        ),
    ]
