# Generated by Django 4.1.7 on 2023-05-04 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_post_job_post_companyjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="CompanyJob",
        ),
    ]
