# Generated by Django 4.1.7 on 2023-05-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_post_companyjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="company_job",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.companyjob",
            ),
            preserve_default=False,
        ),
    ]
