# Generated by Django 4.1.7 on 2023-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_post_company_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="seniority",
            field=models.CharField(
                choices=[
                    ("TR", "Trainee"),
                    ("JR", "Junior"),
                    ("MD", "Middle"),
                    ("SR", "Senior"),
                ],
                max_length=16,
            ),
        ),
    ]
