# Generated by Django 4.1.7 on 2023-05-18 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_post_seniority"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="language",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postsolution",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.post"
            ),
        ),
        migrations.AlterField(
            model_name="postsolution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postsolutionvotes",
            name="postsolution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.postsolution"
            ),
        ),
        migrations.AlterField(
            model_name="postsolutionvotes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postvotes",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.post"
            ),
        ),
        migrations.AlterField(
            model_name="postvotes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
