export enum ERoutes {
  API_BASE_URL = `http://127.0.0.1:8000/api`,
  V1 = `/v1`,
  TOKEN_PREFIX = `/token`,
  USERS_PREFIX = `/users`,
  JOBS_PREFIX = `/jobs`,
  COMPANIES_PREFIX = `/companies`,
  POSTS_PREFIX = `/posts`,
  POSTSOLUTIONS_PREFIX = `/postsolutions`,
  LOGIN = `/login/`,
  REFRESH = `/refresh/`,
  ME = `/me/`,
  VERIFY = `/verify/`,
  LOGOUT = `blacklist/`,
}
